### ISSUE TITLE
No need to wait for data after Wire.requestFrom() and no endTransmission.

### ISSUE THREAD

**Issue by Koepel** [sparkfun/Si4707_Breakout#1]
In the file si4707_system_functions.ino, there is no need for a timeout after the Wire.requestFrom() call. And it should not be followed by a Wire.endTransmission.

When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. The Wire.read() only reads data from that buffer.

**Comment by loricrotser** [comment]
Verified and Fixed.

**Comment by Koepel** [comment]
There is still a timeout after the Wire.requestFrom() in the code. The timeout can be removed.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

When the sensor is not connected (or when there was a bus error), the Wire.available() returns zero. In that case, the timeout will eventually become zero and the data is not read.
However, there is no need for a timeout and a single check is enough to test if the sensor is not connected (or if there was a bus error):
```
void i2cReadBytes(byte number_bytes, byte * data_in)
{
  Wire.requestFrom((byte) SI4707_ADDRESS, number_bytes);
  if(Wire.available() == number_bytes)
  {
    while(number_bytes--)
    {
      *data_in++ = Wire.read();
    }
  }
}
```
